env1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('videopost/', include('videopost.urls')),
]

videopost/urls.py
from django.urls import path

from . import views

app_name = 'videopost'

urlpatterns = [
    path('assignid/', views.assign_unique_id, name='assign_unique_id'),
    path('', views.IndexView.as_view(), name='index'),
    path('pagenatevideo/', views.pagenate_video_query, name='pagenate_video'),
    path('search', views.SerchView.as_view(), name='search'),
    path('edit', views.EditView.as_view(), name='edit'),
    path('check', views.CheckView.as_view(), name='check'),
    path('saveDraft/', views.save_draft, name='save_draft'),
    path('trim/', views.trim_video, name='trim_video'),
    path('posting/', views.posting_video, name='posting_video'),
    path('vpost/', views.video_post, name='video_post'),
    path('account', views.AccountView.as_view(), name='account'),
    path('savenameoraddress/', views.saveNameOrAddress, name="savenoa"),
    path('deletevideo/', views.delete_video, name="delete_video"),
    path('mintvideo/', views.mint_video, name='mint_video'),
    path('changepublic/', views.change_public_or_private, name='change_public'),
    path('sellandcancelnft/', views.sell_and_cancel_nft, name='sell_nft'),
    path('getTags/', views.get_tags, name="get_tags"),
    path('testIpfs/', views.test_ipfs, name="test_ipfs"),
    path('test/', views.test, name='test')
]

"""    
    path('ipost/', views.image_post, name='image_post'),
    path('delete/', views.delete_materials, name='delete'),
    path('saveBackup/', views.save_backup, name='save_backup'),"""

videopost/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.utils import timezone
# Create your models here.


class TagQuerySet(models.QuerySet):
    def append_tag(self, tag):
        """
        append tag to TagModel

        Args:
            tag (str or list): tag to add
        """
        if type(tag) is str:
            tag = [tag]
        tag_objects = [Tag(name=tag_name) for tag_name in tag]
        self.bulk_create(objs=tag_objects, ignore_conflicts=True)
        return tag_objects


class WhenClickQuerySet(models.QuerySet):
    def get_tag_click_value_per_day(self, tag_name=""):
        query_set = self.get_queryset()
        now = timezone.now()
        one_day_ago = now - timezone.timedelta(days=1)
        if tag_name:
            li = list(query_set.filter(date__gte=one_day_ago, date__lte=now).values(
                "tagid").annotate(models.Count("tagid")))
            di = {}
            list(map(lambda x: di.update({x["tagid"]: x["tagid__count"]}), li))
            return di
        else:
            return query_set.filter(date__gte=one_day_ago, date__lte=now, tagid__exact=tag_name).count()


class VideoClickQuerySet(models.QuerySet):
    def get_tag_upload_value(self, tag_name=""):
        query_set = self.get_queryset()
        now = timezone.now()
        one_day_ago = now - timezone.timedelta(days=1)
        if tag_name:
            return list(query_set.filter(uploaded__gte=one_day_ago, uploaded__lte=now))
        else:
            return query_set.filter(tagid__exact=tag_name).count()


class Account(models.Model):
    accountid = models.CharField(max_length=400, primary_key=True)
    walletaddress = models.CharField(max_length=50, blank=True, null=True)
    name = models.CharField(max_length=30, blank=True)


class DeviceMap(models.Model):
    accountid = models.ForeignKey(Account, on_delete=models.CASCADE)
    device = models.CharField(max_length=15)


class BrowserMap(models.Model):
    accountid = models.ForeignKey(Account, on_delete=models.CASCADE)
    browser = models.CharField(max_length=15)


class Tag(models.Model):
    name = models.CharField(max_length=50, primary_key=True)
    totalvalue = models.IntegerField(default=0)
    clickvalue = models.IntegerField(default=0)

    objects = TagQuerySet.as_manager()


class VideoQuerySet(models.QuerySet):
    def get_nft_metadata(self):
        """
        get nft metadata
        """
        return


class Video(models.Model):
    title = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=1000, blank=True)
    video = CloudinaryField(resource_type='video')
    tags = models.ManyToManyField(Tag, related_name="tags", blank=True)
    uploaded = models.DateTimeField(auto_now_add=True)
    uploader = models.ManyToManyField(
        Account, related_name="uploader", blank=True)
    tokenid = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=200, blank=True)
    price = models.FloatField(default=0)
    onedaydelete = models.BooleanField(default=False)
    ispublic = models.BooleanField(default=True)
    views = models.IntegerField(default=0)
    thumbsup = models.IntegerField(default=0)


class TagMap(models.Model):
    videoid = models.ForeignKey("Video", on_delete=models.CASCADE)
    tagid = models.ForeignKey("Tag", on_delete=models.CASCADE, to_field="name")


class whenClick(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    tagid = models.ForeignKey("Tag", on_delete=models.CASCADE, to_field="name")

    objects = WhenClickQuerySet.as_manager()

videopost/forms.py
from django.forms import ModelForm
from django import forms
from .models import Video

class VideoForm(ModelForm):
    class Meta:
        model = Video
        fields = ['video']
        widgets = {
            'video': forms.FileInput(attrs={'accept':'video/*','capture':'environment'})
            }

videopost/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView, ListView
from django.http import JsonResponse
from django.urls import reverse
from django.db.models import Case, When, Value, IntegerField, Count
from django.core.paginator import Paginator
from django.core.serializers import serialize
from .storage import UpdateFileSystemStorage
from .models import Video, Tag, whenClick, TagMap, Account
from .forms import VideoForm
from .nft import Nft
from .aescrypt import aes_gcm_decrypt, aes_gcm_encrypt
from .rsacrypto import generate_key, encrypt, decrypt
from .utils import Cloudinary
from django.utils import timezone
import os
import base64
import moviepy.editor
import uuid
import shutil
import json
from itertools import chain
from cloudinary.uploader import upload
from cloudinary.api import resource
from cloudinary import CloudinaryResource
import requests

# Create your views here.


def get_cloudinary_source(video_name):
    if len(split := video_name.split("/")) != 1:
        print(split)
        video_name = split[2]
    source = resource(video_name, resource_type="video")
    print(source)
    cr = CloudinaryResource(
        source["public_id"], type=source["type"], resource_type=source["resource_type"])
    return cr


def assign_unique_id(request):
    if request.method == "GET":
        public_key, private_key = generate_key()
        public_key = public_key.decode()
        with open("./videopost/temp/private.pem", "wb") as f:
            f.write(private_key)
        return JsonResponse({"public_key": public_key})
    elif request.method == "POST":
        user_id = request.POST.get("userId")
        with open("./videopost/temp/private.pem", "rb") as f:
            private_key = f.read()
            Account.objects.create(
                accountid=user_id, privatekey=private_key.decode())
        return JsonResponse({"response": "success"})


def get_account_list_from_wallet_address_of_user_id(user_id):
    account = Account.objects.get(accountid=user_id)
    return Account.objects.filter(walletaddress=account.walletaddress)


class IndexView(ListView):
    model = Video
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        print(self.request.session.get("user_id"))
        context = super().get_context_data(**kwargs)
        obj = self.model.objects.all().exclude(ispublic=False)
        if tags := self.request.GET.getlist("tag"):
            print(tags)
            for tag in tags:
                obj = obj.filter(tags=tag)
                print(obj)
            context["tags"] = json.dumps(tags)
        elif video_name := self.request.GET.get('videoname'):
            print(video_name)
            cs = get_cloudinary_source(video_name)
            obj = self.model.objects.filter(video=cs) | obj
            context["video_name"] = video_name
        context["video_list"] = serialize("json", obj.order_by('-uploaded'))

        return context

    def get_queryset(self):
        return self.model.objects.all().exclude(ispublic=False).order_by('-uploaded')


def pagenate_video_query(request):
    objects = Video.objects.all().exclude(ispublic=False).order_by('-uploaded')
    print(request.GET)
    if tags := request.GET.get("tags"):
        tags = json.loads(tags)
        for tag in tags:
            objects = objects.filter(tags=tag)
    if video_name := request.GET.get("videoName"):
        if not objects.filter(video=video_name):
            video_name = get_cloudinary_source(video_name)
        print(objects.filter(video=video_name))
        objects = objects.annotate(share=Case(
            When(video=video_name, then=Value(1)), default=Value(0), output_field=IntegerField())).order_by('-share')
    print(objects.values())
    paginator = Paginator(objects, 5)

    page_number = request.GET.get('page')
    if int(page_number) in paginator.page_range:
        page_obj = paginator.get_page(page_number)
        return JsonResponse({'results': serialize('json', page_obj.object_list)})
    else:
        return JsonResponse({'results': False})


class SerchView(ListView):
    model = Tag
    template_name = 'search.html'
    context_object_name = 'tags'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "サーチ"
        return context

    def get_queryset(self):
        return serialize("json", self.model.objects.all())


class EditView(CreateView):
    model = Video
    form_class = VideoForm
    template_name = 'edit.html'

    def get_context_data(self, **kwargs):
        context = super(EditView, self).get_context_data(**kwargs)
        context["title"] = "エディット"
        return context

    def get_success_url(self):
        return reverse('videopost:check')


class CheckView(TemplateView):
    template_name = 'check.html'

    def get_context_data(self, **kwargs):
        context = super(CheckView, self).get_context_data(**kwargs)
        context['title'] = "チェック"
        return context


def save_draft(request):
    if request.method == "POST":
        print(request.POST.get("draft"))
        request.session["draft"] = request.POST.get("draft")
    return JsonResponse({"draft": "success"})


def get_tags(request):
    tags = list(Tag.objects.values_list("name", flat=True))
    print(tags)
    video = Video()
    print(TagMap.objects.filter(tagid__exact="test1(t100,c1500)").count())
    return JsonResponse({"tags": tags})


def trim_video(request):
    if request.method == "POST":
        video_path = request.POST.get("videoPath")
        start_time = request.POST.get("startTime")
        end_time = request.POST.get("endTime")
        path = os.path.join(settings.STATIC_ROOT, video_path[8:].split("?")[0])
        print(start_time)
        print(end_time)
        clip = moviepy.editor.VideoFileClip(path)
        trimed = clip.subclip(float(start_time), float(end_time))
        trimed_path = os.path.join(os.path.dirname(path), "trimed.mp4")
        trimed.write_videofile(trimed_path)
        trimed_path = trimed_path.split("videopost")[1]
        return JsonResponse({"path": trimed_path})


def posting_video(request):
    if request.method == "POST":
        video_path = request.POST.get("path")
        is_delete_one_day = request.POST.get("isDeleteOneDay")
        is_delete_one_day = False if is_delete_one_day == "false" else True
        print(request.POST)
        tags = request.POST.get("tags")
        user_id = request.session.get("user_id")
        print(user_id)
        account = Account.objects.get(accountid=user_id)
        video_path = os.path.join(
            settings.STATIC_ROOT, video_path.split("static/")[1])
        print(video_path)
        upload_response = upload(file=video_path, resource_type="video")
        video_id = upload_response["public_id"]
        created = Video.objects.create(
            video=video_id, onedaydelete=is_delete_one_day)
        if account.walletaddress:
            account_list = Account.objects.filter(
                walletaddress=account.walletaddress)
            created.uploader.add(*account_list)
        else:
            created.uploader.add(account)
        if tags:
            tag_objects_list = Tag.objects.append_tag(tags.split(","))
            created.tags.add(*tag_objects_list)
        return JsonResponse({"response": "success"})


class AccountView(ListView):
    template_name = 'account.html'
    context_object_name = "video_list"
    model = Video

    def get_context_data(self, **kwargs):
        context = super(AccountView, self).get_context_data(**kwargs)
        context['title'] = "アカウント"
        user_id = self.request.session.get("user_id")
        nft_list = self.model.objects.filter(
            uploader__accountid=user_id).exclude(tokenid=None)
        # nft = Nft()
        # print(nft_list.values_list("tokenid")[0][0])
        # metadata_list = [nft.get_nft_metadata(token_id[0]) for token_id in video_list.values_list("tokenid")]
        # print(metadata_list)
        print(nft_list)
        print(self.request.session["user_id"])
        context['nft_list'] = serialize("json", nft_list)
        account = Account.objects.get(accountid=user_id)
        context['address'] = account.walletaddress if account.walletaddress else ""
        context['name'] = account.name if account.name else ""

        user_id = self.request.session.get("user_id")
        account = Account.objects.get(accountid=user_id)
        # context['test'] = json.dumps(list(map(Cloudinary.get_cloudinary_data, json.loads(serialize("json", self.model.objects.filter(
        #     uploader=account).order_by('-uploaded'))))))
        context['test'] = serialize("json", self.model.objects.filter(
            uploader=account).order_by('-uploaded'))

        return context

    def get_queryset(self, **kwargs):
        user_id = self.request.session.get("user_id")
        account = Account.objects.get(accountid=user_id)
        return serialize("json", self.model.objects.filter(uploader=account).order_by('-uploaded'))


def saveNameOrAddress(request):
    name = request.POST.get('name')
    address = request.POST.get('address')
    user_id = request.session.get("user_id")
    print(address, name)
    account = Account.objects.get(accountid=user_id)
    before_address_list = Account.objects.filter(
        walletaddress=account.walletaddress)
    # before_address_list = get_account_list_from_wallet_address_of_user_id(user_id)
    if address:
        before_address_list.update(walletaddress=address)
        after_account_list = Account.objects.filter(walletaddress=address)
        # print(set([video_object for acc in after_account_list if (
        #     video_object := Video.objects.filter(uploader=acc))]))
        user_video_queryset = Video.objects.filter(uploader=account)
        user_video_queryset = Video.objects.filter(
            uploader=after_account_list[0])

videopost/templates/check.html
<!--ひとつ前のページへ戻る 好きに使って！-->

<html>
  <head>
    <title>サンプルページ</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% csrf_token %}
    <link rel="stylesheet" href='https://unpkg.com/@acab/reset.css'>
    <link rel="stylesheet" href="{% static 'css/check.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/@vueuse/shared"></script>
    <script src="https://unpkg.com/@vueuse/core"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script type="module" src="{% static 'js/check.js' %}" defer></script>
  </head>

  <body>
    <div id="check">
      <div id="sessions">
        <div id="draft" ref="draftElement" data-draft="{{ request.session.draft }}"></div>
      </div>

      <div id="header">
        <a href="{{request.META.HTTP_REFERER}}">前のページに戻る</a>
        <a href="{% url 'videopost:index' %}">×</a>
      </div>

      <section id="preview">
        <video id="ajvideoPlayer" :src="videoSrc" ref="videoPreview" @loadedmetadata="loadVideo"></video>
      </section>

      <section id="timelines">
        <div id="util">
          <div id="play" v-show="!playFlag" @click.stop="playVideo"></div>
          <div id="stop" v-show="playFlag" @click.stop="pauseVideo">
            <div></div>
            <div></div>
          </div>
          <p>[[ displayCurrentTime.current ]] / [[ displayCurrentTime.duration ]]</p>
        </div>
        <div id="timeline" ref="timelineElement" @mousedown.prevent="moveCurrent" :style="{width:timelineWidth, left:timelineLeft}">
          <div id="currentTime" :style="{left:currentTimePosition+'%'}"></div>
          <div id="times">
              <div v-for="(item,index) in intervalList" :style="{left:item.left}" :id="'time'+index" class="time">
                  [[item.displayTime]]
              </div>
          </div>
        </div>
        <div id="material" ref="material" :style="{width:materialWidth, left:materialLeft}" @mousedown.prevent="move">
          <div id="leftHandle" class="handle" ref="leftHandle" :style="{left:handleLefts.l}" @mousedown.prevent.stop="resize"></div>
          <div id="rightHandle" class="handle" ref="rightHandle" :style="{left:handleLefts.r}" @mousedown.prevent.stop="resize"></div>
        </div>
      </section>
      
      <section id="footer">
        <input id="videoInput" type='file' accept='video/*' @change="selectVideo" style="display: none;">
        <label for="videoInput" class="custom-file-upload"><img src="{% static 'images/edit.png'%}" style="height: 20;"></label>
        <button id="post" @click="trim">次へ</button>
      </section>

      <button @click="togglelastcheck" style="position:absolute; z-index:9998;">button</button>
      <div id="lastCheck">
        <button @click="togglelastcheck">toggle</button>
        <div id="fuzzySearch">
          <input type="search" v-model="inputTag" id="tagInput" ref="tagInputElement">
          <button @click="addTag">追加</button>
          <ul id="searchPrediction" @click="predict">
            <li v-for="history in historys" v-show="inputTag"><div id="historyMark"></div>[[ history ]]</li>
            <li v-for="tag in results">[[ tag.item ]]</li>
          </ul>
        </div>
        <div id="tags" :style="{width:tagsWidth}">
          <div v-for="name in tags" class="tag">
            [[ name ]]
            <p @click="tagDelete">×</p>
          </div>
        </div>
        <video id="lastCheckVideo" ref="lastCheckVideo" controls></video>
        <div>
          <label for="isDeleteOneDay" style="display:inline-flex; padding: 10;">1日で消す<input id="isDeleteOneDay" class="switch" type="checkbox" v-model="isDeleteOneDay"></input></label>
          <button @click="post">投稿</button>
        </div>
      </div>
      </div>
    </div>
  </body>
</html>

videopost/templates/index.html
<html>
  <head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width">
    {% load static %}
    <link rel="icon" href="{% static 'images/main-logo.svg' %}">
    <link rel="stylesheet" href='https://unpkg.com/@acab/reset.css'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/tag.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'css/loader.css' %}"> {% endcomment %}
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Modaal/0.4.4/css/modaal.min.css">
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/vue@3.2.31/dist/vue.global.prod.js"></script>
    <script src="https://unpkg.com/@vueuse/shared"></script>
    <script src="https://unpkg.com/@vueuse/core"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script type="module" src="{% static 'js/scroll.js' %}" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/cloudinary-core@2.10.3/cloudinary-core-shrinkwrap.min.js"></script>
    <title>トップページ</title>
  </head>
  <body>


    <div id="scroll">
      <div>
        <div data-tags="{{ tags }}" data-video="{{ video_name }}" ref="loadElement"></div>
      </div>
      <div id="splash" :class="{'fadeDown': fadeDownFlag}">
        <div id="splash_logo">
          <img src="{% static 'images/header.svg'%}" alt="" :class="{'fadeUp' : fadeUpFlag}">
        </div>
        <div id="loader" :class="{'fadeUp' : fadeUpFlag}">
          {% include "loader.html" %}
        </div>
      </div>

      <div id="wrapper">

      {% comment %} <div class="loading">
        <img src="{% static 'images/header.svg'%}" alt="loading_pic">
        <div class="spinner"></div>
        
      </div> {% endcomment %}
      <div class="tutorial" v-if="tutorialFlag" @click.stop="onTutorialClick">
        <div class="scrolldown2">
          {% comment %} <span>メニュー画面の表示は左にスワイプ</span> {% endcomment %}
        </div>
        <div class="rippless_btn">
          <div></div>
        </div>
      </div>


        <div id="fixed">
          <div id="leftMenu" :class="{ 'menuInTutorial': tutorialFlag, 'menuTransition': transitionFlag }" ref="menu" :style="{right: menuRight+'%', opacity: menuOpacity}">
            <div id="menuContainer">
              <div class="logo">
                <img src="{% static 'images/main_text.svg'%}" alt="ロゴ">
              </div>
              
              <div id="header">




                  <div class="transaction">
                    <div class="price">
                      <h3>price</h3>

                    </div>
                      <div class="buy">
                        <p v-if="dataList[currentVideoIndex].price" class="by_txt">[[ dataList[currentVideoIndex].price ]]</p>
                        <p v-else class="by_txt">無し</p>
                        <img src="{% static 'images/buy_icon.png'%}" class="buy_icon" alt="buy">
                      </div>
                    </div>

                    <div class="info">
                      {% comment %} <p id="info_name">info</p> {% endcomment %}
                      <h3>title</h3>
                      <div class="title_message">
                        <p v-if="dataList[currentVideoIndex].title">[[ dataList[currentVideoIndex].title ]]</p>
                        <p v-else>無し</p>
                      </div>
                      <h3>description</h3>
                      <div class="description_message">
                        <p v-if="dataList[currentVideoIndex].description">[[ dataList[currentVideoIndex].description ]]</p>
                        <p v-else>無し</p>
                      </div>
                      {% comment %} <p>[[ dataList[currentVideoIndex].video]]</p> {% endcomment %}

                      
                    </div>




                {% comment %} <div id="trade">
                  <img src="{% static 'images/NFTgraph.png'%}" alt="tests">
                </div> {% endcomment %}
                <div class="trade" >
                    <div id="buttton">
                        <div id="good">
                          <a href="{% url 'videopost:index' %}"><img src="{% static 'images/good_icon.svg'%}" alt="good"></a>
                        </div>

                        <div id="share">
                          <a href="{% url 'videopost:index' %}"><img src="{% static 'images/share_icon.svg'%}" @Click="shareLink" alt="share"></a>
                        </div>

                    
                    <div id="ug">
                      <h3>upload</h3>
                      <div class="uploaded_date">
                        <p v-if="dataList[currentVideoIndex].uploaded">
                          [[
                            new Date(dataList[currentVideoIndex].uploaded).toLocaleString('ja-JP', {year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Tokyo'})
                          ]]
                        </p>
                        <p v-else>無し</p>
                      </div>
      
                      <h3>tags</h3>
                      <div class="tags_message">
                        <div v-if="dataList[currentVideoIndex].tags.length">
                          <p class="search-tag" v-for="tag in dataList[currentVideoIndex].tags">
                            <div id="tag-before" @click="deleteTag(tag)" class="icon-circle"></div>
                            [[ tag ]]
                          </p>
                        </div>
                        <p v-else>無し</p>
                      </div>

                    </div>
                    
                    </div>
                </div>
              </div>
                <div id="buttons">

                  <div class="serch">
                    <a href="{% url 'videopost:search' %}"><img src="{% static 'images/search_icon.png'%}" alt="検索"></a>
                  </div>

                  <div class="edit">
                    <!--<a href="{% url 'videopost:edit' %}"><img src="{% static 'images/edit.png'%}" alt="投稿"></a>-->
                    <a href="{% url 'videopost:check' %}"><img src="{% static 'images/edit.png'%}" alt="投稿"></a>
                  </div>
                </div>
              
                

            </div>
        </div>
      
      <div class="infinite-container" id="container" ref="container">
        <!--動画要素の表示-->
        <div v-for="(video,index) in dataList" class="infinite-item">
          <video playsinline :src="blobVideos[index]" height="100%" autoplay loop @click.prevent="togglePlayAndGood"></video>
        </div>
        {% comment %} {% comment %} {% for video in object_list %}
        <section class="infinite-item">
            <p style="width:70%; word-wrap:break-word;">{{ video.title }}</p>
            <video playsinline src="https://res.cloudinary.com/dhlsaygev/video/upload/{{ video.video }}.mp4" height="100%" autoplay></video>
            <!--動画の上に画像の表示-->
            <div class="overlay"></div>
        </section>
        {% endfor %} {% endcomment %}
      </div>
    </div>
    </div>
 </body>
</html>

videopost/templates/loader.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/loader.css' %}">

<div class="self-building-square-spinner">
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square clear"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square clear"></div>
    <div class="square"></div>
    <div class="square"></div>
  </div>

videopost/templates/search.html
<html>
  <head>
    <title>サンプルページ</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href='https://unpkg.com/@acab/reset.css'>
    <link rel="stylesheet" href="{% static 'css/tag.css' %}">
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/@vueuse/shared"></script>
    <script src="https://unpkg.com/@vueuse/core"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script type="module" src="{% static 'js/search.js' %}" defer></script>
  </head>

  <body>
    <div id="app" v-cloak>
      <div>
        <div data-tags="{{ tags }}" ref="loadElement"></div>
      </div>

      <section id="searchContainer">
        <div id="fuzzySearch">
          <div style="display:flex;">
            <div class="tag-input-wrapper" style="overflow: hidden;">
              <input type="search" v-model="inputTag" id="tagInput" ref="tagInputElement">
            </div>
            <button @click="addSearchTag">add</button>
          </div>
          <ul id="searchPrediction" @click.stop="predict">
            <li v-for="history in historys" v-show="inputTag"><div id="historyMark"></div>[[ history ]]</li>
            <li v-for="tag in results">[[ tag.item ]]</li>
          </ul>
        </div>
      </section>

      <section style="display: flex;">
        <div class="search-tag" v-for="tag in searchTags" @click="toggleTagBefore(tag)">
          <div id="tag-before" @click="deleteTag(tag)" :class="{'icon-close': tag.flag, 'icon-circle': !tag.flag}"></div>
          [[ tag.name ]]
        </div>
      </section>

      <section class="searchButton">
        <form action="{% url 'videopost:index' %}" method="get" ref="form">
          <input type="hidden" v-for="tag in searchTags" :value="tag.name" name="tag"></input>
        </form>
        <button @click.prevent="search">検索</button>
      </section>

    </div>
  </body>
</html>

videopost/templates/video.html
{% load static %}

<!--ひとつ前のページへ戻る 好きに使って！-->
<a href="{{request.META.HTTP_REFERER}}">前のページに戻る</a>

<html>
  <head>
    <title>サンプルページ</title>
    <meta charset='utf-8'>
    <link rel="stylesheet" href="{% static 'css/video.css' %}">
    <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/video.js' %}"></script>
  </head>
  <body>
    <button id="startButton">Start Recording</button>
    <button id="stopButton" disabled>Stop Recording</button>
    <br>
    <video id="videoElement" width="400" height="300" autoplay></video>

    <form id="uploadForm" method="post" action="{% url 'videopost:video_post' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="videoData" id="videoData">
        <input type='hidden' name='tempdir' id='tempdir' value="{{ tempdir }}">
        <input type="submit" value="Submit" hidden>
    </form>
  </body>
</html>